AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura DevOps con EC2 y S3 para Learner Lab

Resources:
  DevOpsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      IamInstanceProfile: LabInstanceProfile
      SubnetId: subnet-04ca4127ef3c7f95a
      SecurityGroupIds:
        - sg-029642d18afcfc952
      Tags:
        - Key: Name
          Value: DevOps-EC2-CloudFormation

  DevOpsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'devops-bucket-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

Outputs:
  InstanceId:
    Description: ID de la instancia EC2 creada
    Value: !Ref DevOpsInstance

  BucketName:
    Description: Nombre del bucket S3 creado
    Value: !Ref DevOpsBucket
